[package]
name = "dupliwise"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0", features = ["derive"] }
hex = "0.4.3"
openssl = "0.10.62"
walkdir = "2.4.0"

